### Setup for the maze environment

In [12]:
import numpy as np
from random import random

In [51]:
class Environment:
    def __init__(self):
        # create a maze
        self.maze = np.zeros((10, 10))
        
        # dimensions of the maze
        self.maze_width = 9
        self.maze_height = 9
        
        # add the current (at the start at beginning) and end points
        self.current_point_x = 0
        self.current_point_y = 0
        self.end_point_x = self.maze_height
        self.end_point_y = self.maze_width
        
        self.add_walls()
    
    # add the walls to the environment so that the agent cannot go through those
    def add_walls(self):
        pass
    
    # move the agent
    def move(self, direction):
        # agent cannot move if already at an edge
        if direction == "left":
            if self.current_point_x > 0:
                self.current_point_x -= 1
        elif direction == "right":
            if self.current_point_x < self.maze_width - 1:
                self.current_point_x += 1
        elif direction == "up":
            if self.current_point_y > 0:
                self.current_point_y -= 1
        elif direction == "down":
            if self.current_point_y < self.maze_height - 1:
                self.current_point_y += 1

    # test out by making some random moves
    def do_moves(self):
        moves = []
        for i in range(10):
            r = random()
            if r < 0.25:
                moves.append("left")
            elif r < 0.5:
                moves.append("right")
            elif r < 0.75:
                moves.append("up")
            else:
                moves.append("down")
            self.move(moves[-1])
            self.maze[self.current_point_y, self.current_point_x] = 1
        
        print(moves)
        print(self.maze)
                

In [52]:
env = Environment()
env.do_moves()

['down', 'left', 'left', 'down', 'up', 'right', 'up', 'left', 'down', 'up']
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
